"""add knowledge source file metadata fields

Revision ID: 99708fe1f586
Revises: 2563348e1acc
Create Date: 2026-03-21 13:29:54.710502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99708fe1f586'
down_revision: Union[str, None] = '2563348e1acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('knowledge_sources', sa.Column('original_filename', sa.String(length=500), server_default='', nullable=False))
    op.add_column('knowledge_sources', sa.Column('file_type', sa.String(length=50), server_default='', nullable=False))
    op.add_column('knowledge_sources', sa.Column('file_size', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('knowledge_sources', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_sources', 'updated_at')
    op.drop_column('knowledge_sources', 'file_size')
    op.drop_column('knowledge_sources', 'file_type')
    op.drop_column('knowledge_sources', 'original_filename')
    # ### end Alembic commands ###
